---
title: "演習課題"
output: html_document
date: "2025-06-03"
---
```{r}
library(tidyverse)

d <- data.frame(
  name = c("太郎", "花子", "三郎", "良子", "次郎", "桜子", "四郎", "松子", "愛子"),
  school = c("南", "南", "南", "南", "南", "東", "東", "東", "東"),
  teacher = c("竹田", "竹田", "竹田", "竹田",  "佐藤", "佐藤", "佐藤", "鈴木", "鈴木"),
  gender = c("男", "女", "男", "女", "男", "女", "男", "女", "女"),
  math = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
  reading = c(1, 5, 2, 4, 5, 4, 1, 5, 4) )

d
```
```{r}
d |> select(name,math)
```
```{r}
d |> select(name,school,teacher,math,reading)
```
```{r}
d |> slice(3:6)
```
```{r}
d |> arrange(name)
```
```{r}
d |> arrange(desc(math))
```
```{r}
d |> arrange(desc(math),desc(reading))
```
```{r}
d |> select(name,reading)
```
```{r}
d |> summarize(mean(math))
```
```{r}
d |> group_by(teacher) |> summarize(math_mean = mean(math))
```
```{r}
d |> filter(gender == "女") |> select(name,math)
```
```{r}
d |> filter(gender == "男") |> select(reading)
```
```{r}
d |> group_by(teacher) |> filter(n() >=3) |> ungroup()
```
```{r}
d <- d |> mutate(total = math + reading)
d
```
```{r}
d <- d |> mutate(math100 = math / 5 * 100)

d
```

